/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    Contact: typeof import('./src/components/Contact.vue')['default']
    FadeOnKey: typeof import('./src/components/FadeOnKey.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Motion: typeof import('motion-v')['Motion']
    Projects: typeof import('./src/components/Projects.vue')['default']
    Reveal: typeof import('./src/components/Reveal.vue')['default']
    RevealGroup: typeof import('./src/components/RevealGroup.vue')['default']
    SectionHeading: typeof import('./src/components/SectionHeading.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    TextSplit: typeof import('./src/components/TextSplit.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    YearLabel: typeof import('./src/components/YearLabel.vue')['default']
  }
}
